version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: db_postgres
        restart: always
        environment:
            POSTGRES_DB: panorama
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spring_app
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/panorama
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
    pgdata:
